config/routes.rb
Onestep::Application.routes.draw do

  root :to => 'info#marketing'
  get '/api/money'  => 'api#money'

  get 'timeline' => "activities#timeline", as: "timeline"

  post '/checkout' => "orders#checkout"
  get '/orders/done' => "orders#done"
  post '/orders/notify' => "orders#notify"
  get "/orders/new" => "orders#new",  :as => "new_order"
  get "/download" => "videos#download", :as => "download_video"

  get "about" => "about#main", :as => "about"
  get "about/team" => "about#team"
  get "about/jobs" => "about#jobs"
  get "about/faq" => "about#faq"
  get "/set_locale" => "info#set_locale"
  get "/styleguide/css(/:ref)" => "info#styleguide"

  get "/blog" => "posts#index", :as => "blogs"
  get "/blog/:id" => "posts#show", :as => "blog"
  get "/blog/:id/edit" => "posts#edit", :as => "edit_blog"
  get "/write_blog" => "posts#new"

  # Use patch verb for editing posts, use put verb for creating a new post
  match 'blog_images', to: 'blog_images#create', via: [:put, :patch]

  resources :posts
  resources :blog_images
  resources :videos
  resources :password_resets

  get "notifications" => "notifications#index", :as => "notifications"
  delete "notifications/:id" => "notifications#destroy", :as => "notification"
  delete "notifications" => "notifications#clear", :as => "clear_notifications"

  patch '/restore_gravatar' => "users#restore_gravatar"
  patch 'edit-avatar' => 'users#update_avatar', :as => :update_avatar
  get "edit-avatar" => "users#edit_avatar", :as => "edit_avatar"
  patch 'update_poster' => 'courses#update_poster', :as => :update_poster

  resources :comments
  post "/comment_preview" => "comments#preview", :as => "comment_preview"

  get "login" => "users#login", :as => "login"
  get "signup" => "users#signup", :as => "signup"
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"

  patch "/course" => "courses#update"
  get "/course" => "courses#index", :as => "course_index"
  post "/course" => "courses#create"
  get "/create_course" => "courses#new", :as => :create_course

  get "/members" => "users#index", :as => "user_index"
  post "/members" => "users#create"
  put "/crop" => "users#crop", :as => "crop"
  put "/crop_poster" => "courses#crop_poster", :as => "crop_poster"

  get "/:member_name/:course_name/timeline" => "activities#index" , :as => "timeline_course"

  post "/:member_name/:course_name/watch" => "courses#watch"
  post "/:member_name/:course_name/unwatch" => "courses#unwatch"
  get "/:member_name/:course_name/watchers" => "courses#watchers", :as => "course_watchers"

  get "/:member_name/:course_name/collaboration" => "courses#collaboration", :as => "course_collab"

  post "/:member_name/:course_name/add_member" => "courses#add_member", :as => "course_add_member"
  post "/:member_name/:course_name/delete_member" => "courses#delete_member", :as => "course_delete_member"

  resources :courses, :except => :edit do
    get :autocomplete_user_name, :on => :collection
  end

  post "/:member_name/follow" => "users#follow"
  post "/:member_name/unfollow" => "users#unfollow"

  get "/account" => "users#edit", :as => "account"
  patch "/account" => "users#update"
  get "/:member_name" => "users#show", :as => "member"
  delete "/:member_name/:course_name" => "courses#destroy"
  get "/:member_name/:course_name(/:position)" => "courses#show", :constraints => {:position => /\d+/} # "/:xxx/:xxx" will conflict with many things, so have to put bottom
  patch "/update_video/:id" => "videos#update"
  post "/sort_videos" => "videos#sort"

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :executor, :class_name => 'User'
  belongs_to :notifiable, :polymorphic => true

  scope :recent, -> { order("created_at DESC") } 

  attr_accessible :action, :unread, :notifiable, :user, :executor

  def self.notify(user, notifiable, executor, unread = true, action)
    n = Notification.new user: user, notifiable: notifiable
    n.action = action
    n.unread = unread
    n.executor = executor
    n.save
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  after_filter :mark_read, :only => :index

  def index
    @notifications = current_user.notifications.recent.page(params[:page]).per(30)
  end
  def destroy
    @notification = current_user.notifications.find(params[:id])
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_path }
    end
  end
  def clear
    current_user.notifications.delete_all
    respond_to do |format|
      format.html { redirect_to notifications_path }
    end
  end
  def mark_read
    current_user.notifications.update_all(unread: false)
  end
end

app/views/notifications/_notification_activity.html.erb
<% activity = notification.notifiable %>
<% action = notification.action %>
<% executor = notification.executor %>

<% case action %>
<% when "destroy" %>
<td class="notificon">
  <i class="fa fa-trash-o fa-2x"></i>
</td>
<td class="avatar">
  <%= link_to member_path(executor.name) do %>
    <%= image_tag executor.final_avatar_url, :class => "gavatar", :width => "30x30" %>
  <% end %>
</td>
<td class="event">
  <%= render :partial => "notification_executor", :locals => { :notification => notification} %>
  <span class="annotate"> 删除了一个视频</span>
</td>
<% when "create", "update" %>
  <% if activity.trackable.present? %>
    <td class="notificon">
      <i class="fa <%= action == "create" ? "fa-plus" : "fa-edit" %> fa-2x"></i>
    </td>
    <td class="avatar">
      <%= link_to member_path(executor.name) do %>
        <%= image_tag executor.final_avatar_url, :class => "gavatar", :width => "30x30" %>
      <% end %>
    </td>
    <td class="event">
      <%= render :partial => "notification_executor", :locals => { :notification => notification} %>
      <% if action == "create" %>
        <span class="annotate"> 上传一个新视频： </span>
      <% else %>
        <span class="annotate"> 更新了视频： </span>
      <% end %>
      <%= video_course_path(activity.trackable) %>
    </td>
  <% end %>
<% end %>

app/views/notifications/_notification_comment.html.erb
<% commentable = notification.notifiable.commentable %>
<% executor = notification.executor %>

<% case commentable.class.name.underscore %>
<% when "video" %>
  <td class="notificon"><i class="fa fa-comments fa-2x"></i></td>
  <td class="avatar">
    <%= link_to member_path(executor.name) do %>
      <%= image_tag executor.final_avatar_url, :class => "gavatar", :width => "30x30" %>
    <% end %>
  </td>
  <td class="event">
    <%= render :partial => "notification_executor", :locals => { :notification => notification } %>
    <% course = commentable.course %>
    <span class="annotate">
      <%= course.user == current_user ? '评论了你的课程' : '评论了你点评过的课程' %>
      (<%= link_to course.title, course_path(course) %>)的第
      <%= commentable.position %>个视频
      <%= link_to commentable.title, commentable_comment_path(notification.notifiable.id) %>
    </span>
    <div class="comment-body markdown-format">
      <%= markdown notification.notifiable.content %>
    </div>
  </td>
  <% when "post" %>
  <td class="notificon"><i class="fa fa-comments-o fa-2x"></i></td>
  <td class="avatar">
    <%= link_to member_path(executor.name) do %>
      <%= image_tag executor.final_avatar_url, :class => "gavatar", :width => "30x30" %>
    <% end %>
  </td>
  <td class="event">
    <%= render :partial => "notification_executor", :locals => { :notification => notification } %>
    <span class="annotate">
      <%= commentable.user == current_user ? '评论了你的文章' : '评论了你点评过的文章' %>
      <%= link_to commentable.title, blog_path(commentable) %>
    </span>
    <div class="comment-body markdown-format">
      <%= markdown notification.notifiable.content %>
    </div>
  </td>
<% end %>

app/views/notifications/_notification_course.html.erb
<% executor = notification.executor %>

<% case notification.action %>
<% when "watch" %>
  <td class="notificon"><i class="fa fa-eye fa-2x"></i></td>
  <td class="avatar">
    <%= link_to member_path(executor.name) do %>
      <%= image_tag executor.final_avatar_url, :class => "gavatar", :width => "30x30" %>
    <% end %>
  </td>
  <td class="event">
    <%= render :partial => "notification_executor", :locals => { :notification => notification } %>
    <% course = notification.notifiable %>
    <span class="annotate">关注了你的课程: </span>
    <%= link_to course.title, course_path(course) %>
  </td>
<% end %>

app/views/notifications/_notification_executor.html.erb
<% executor = notification.executor %>

<%= link_to member_path(executor.name) do %>
  <span><%= executor.name %></span>
<% end %>
<% if notification.notifiable_type == "Activity" %>
  <span class="annotate">为你关注的课程： </span>
  <%= course_name_tag(notification.notifiable.course_id) %>
<% end %>

app/views/notifications/index.html.erb
<div id="notifications">
  <div class="container details">
    <div class="title">
      <div class="clear-all">
        <%= link_to "清空", clear_notifications_path, :method => "delete", :class => "btn-danger" %>
      </div>
      <div class="total">通知提醒<small> (<%= @notifications.count %> 条)</small></div>
    </div>
    <% if @notifications.blank? %>
      <div class="no-content">
        暂无通知
      </div>
    <% else %>
      <table class="content">
        <tbody>
          <% @notifications.each do |notification| %>
              <% type = notification.notifiable_type.underscore %>
              <tr class="<%= cycle("odd", "even") %><%= " highlight" if notification.unread %>">
                <%= render :partial => "notification_#{type}", :locals => { :notification => notification }%>
                <td class="time"><%= time_ago_in_words notification.created_at %>前</td>
                <td class="last"><%= link_to "删除", notification_path(notification),
                  :method => "delete", :class => "danger" %></td>
              </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <%= paginate @notifications, :window => 2 %>
  </div>
</div>