config/routes.rb
Onestep::Application.routes.draw do

  root :to => 'info#marketing'
  get '/api/money'  => 'api#money'

  get 'timeline' => "activities#timeline", as: "timeline"

  post '/checkout' => "orders#checkout"
  get '/orders/done' => "orders#done"
  post '/orders/notify' => "orders#notify"
  get "/orders/new" => "orders#new",  :as => "new_order"
  get "/download" => "videos#download", :as => "download_video"

  get "about" => "about#main", :as => "about"
  get "about/team" => "about#team"
  get "about/jobs" => "about#jobs"
  get "about/faq" => "about#faq"
  get "/set_locale" => "info#set_locale"
  get "/styleguide/css(/:ref)" => "info#styleguide"

  get "/blog" => "posts#index", :as => "blogs"
  get "/blog/:id" => "posts#show", :as => "blog"
  get "/blog/:id/edit" => "posts#edit", :as => "edit_blog"
  get "/write_blog" => "posts#new"

  # Use patch verb for editing posts, use put verb for creating a new post
  match 'blog_images', to: 'blog_images#create', via: [:put, :patch]

  resources :posts
  resources :blog_images
  resources :videos
  resources :password_resets

  get "notifications" => "notifications#index", :as => "notifications"
  delete "notifications/:id" => "notifications#destroy", :as => "notification"
  delete "notifications" => "notifications#clear", :as => "clear_notifications"

  patch '/restore_gravatar' => "users#restore_gravatar"
  patch 'edit-avatar' => 'users#update_avatar', :as => :update_avatar
  get "edit-avatar" => "users#edit_avatar", :as => "edit_avatar"
  patch 'update_poster' => 'courses#update_poster', :as => :update_poster

  resources :comments
  post "/comment_preview" => "comments#preview", :as => "comment_preview"

  get "login" => "users#login", :as => "login"
  get "signup" => "users#signup", :as => "signup"
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"

  patch "/course" => "courses#update"
  get "/course" => "courses#index", :as => "course_index"
  post "/course" => "courses#create"
  get "/create_course" => "courses#new", :as => :create_course

  get "/members" => "users#index", :as => "user_index"
  post "/members" => "users#create"
  put "/crop" => "users#crop", :as => "crop"
  put "/crop_poster" => "courses#crop_poster", :as => "crop_poster"

  get "/:member_name/:course_name/timeline" => "activities#index" , :as => "timeline_course"

  post "/:member_name/:course_name/watch" => "courses#watch"
  post "/:member_name/:course_name/unwatch" => "courses#unwatch"
  get "/:member_name/:course_name/watchers" => "courses#watchers", :as => "course_watchers"

  get "/:member_name/:course_name/collaboration" => "courses#collaboration", :as => "course_collab"

  post "/:member_name/:course_name/add_member" => "courses#add_member", :as => "course_add_member"
  post "/:member_name/:course_name/delete_member" => "courses#delete_member", :as => "course_delete_member"

  resources :courses, :except => :edit do
    get :autocomplete_user_name, :on => :collection
  end

  post "/:member_name/follow" => "users#follow"
  post "/:member_name/unfollow" => "users#unfollow"

  get "/account" => "users#edit", :as => "account"
  patch "/account" => "users#update"
  get "/:member_name" => "users#show", :as => "member"
  delete "/:member_name/:course_name" => "courses#destroy"
  get "/:member_name/:course_name(/:position)" => "courses#show", :constraints => {:position => /\d+/} # "/:xxx/:xxx" will conflict with many things, so have to put bottom
  patch "/update_video/:id" => "videos#update"
  post "/sort_videos" => "videos#sort"

end

app/views/shared/_fileupload_widget.html.haml
- content_for :template_js do
  = javascript_include_tag 'i_fileupload'
  :javascript
    jQuery(function($) {
      var textarea = $("#{textarea_selector}");
      var _tip = $("#upload-tip");
      $('#fileupload').fileupload({
          dataType: 'json',
          url: '/blog_images.json',
          maxFileSize: 1024 * 1024 * 5,
          add: function(e, data){
            types = /(\.|\/)(gif|jpe?g|png)$/i;
            file = data.files[0];
            if (types.test(file.type) || types.test(file.name))
            {
              data.submit();
            }
            else
            {
              alert(file.name + " is not a image file");
            }
          },
          start: function(e) {
            _tip.html('图片上传中&nbsp;&middot;&middot;&middot;');
          },
          done: function (e, data) {
              $.each(data.result, function (index, file) {
                new_pic = "\n" + "![](" + file.url + ")";
                source = textarea.val();
                pos = Math.max(textarea.caret('pos'), 0);
                startStr = source.slice(0, pos);
                endStr = source.slice(pos);
                text = startStr + new_pic + endStr;
                textarea.val(text);
                textarea.caret('pos', startStr.length + new_pic.length);
                textarea.focus();
              });
          },
          always: function(e) {
            _tip.html("上传图片");
          },
      });
    });

.pull-right
  %a.fileupload-btn.action_label
    %span#upload-tip 上传图片
    %input#fileupload{:type => 'file', :multiple => true, :name => "blog_image[asset][]"}

app/views/shared/_header_logged_in.html.erb
<div class="header header-logged-in">
  <div class="container clearfix">
    <a class="header-logo-wordmark" href="/">
      HAOQI
    </a>
    <ul class="top-nav">
      <li> <%= link_to "全部课程", course_index_path(:sort => "star") %></li>
      <li><a href="/timeline"><%= t("site_timeline") %></a></li>
      <li><a href="/blog"><%= t("blog") %></a></li>
			<li><a href="/about"><%= t("about") %></a></li>
    </ul>
    <ul id="user-links">
      <li><%= link_to notifications_path do %>
        <span class="notification-indicator <%= 'notification-indicator-unread' if @unread_count > 0 %>"><%= @unread_count %></span>
      <% end %>
      </li>
      <li> <%= link_to current_user.name, member_path(current_user.name), :class => "name" %> </li>
      <li> <%= link_to t("logout"), logout_path, method: "delete" %></li>
    </ul>
  </div>
</div>

app/views/shared/_header_logged_out.html.erb
<div class="header header-logged-out">
  <div class="container clearfix">
    <a class="header-logo-wordmark" href="/">
      HAOQI
    </a>

    <ul class="top-nav">
      <li><a href="/about"><%= t("about") %></a></li>
      <li><a href="/blog"><%= t("blog") %></a></li>
      <li><a href="/timeline"><%= t("site_timeline") %></a></li>
    </ul>

    <div class="header-actions">
      <%= link_to t('sign_in'), login_path, class:"button" %>
    </div>

  </div>
</div>

app/views/shared/_home_masthead.html.erb
<div class="masthead">
  <div class="container">
    <div class="home-signup">
      <%= render 'shared/home_signup_form' %>
    </div>
    <%= render 'shared/tagline' %>
  </div>
</div>

app/views/shared/_home_signup_form.erb
<%= form_for(@user,:url => "/members", :class => "home-signup") do |f|  %>
  <dl class="form">
    <dd>
    <%= f.text_field :name, :placeholder => t('signup_username'), :class => "short" %>
    </dd>
  </dl>
  <dl class="form">
    <dd>
      <%= f.text_field :email, :placeholder => "Email", :class => "short" %>
    </dd>
  </dl>
  <dl class="form">
    <dd>
      <%= f.password_field :password, :placeholder => t('password'), :class => "short" %>
    </dd>
  </dl>
  <p class="text-muted">注册后就可以关注你喜欢的课程了</p>
  <p><%= f.submit t("signup_free"), :class => "button button-block primary" %></p>
<% end %>

app/views/shared/_marketing.html.erb
<div class="container clearfix">

  <div class="marketing">
    <h1>好奇猫的课程</h1>
    <ul class="sort-label clearfix">
      <li class="active" data-type="star"><a href="#">按课程关注人数排序</a></li>
      <li data-type="time"><a href="#">按课程创建时间排序</a></li>
    </ul>
    <div id="sorted-by-star">
      <% if !@star_courses.empty? %>
        <div class="courses clearfix">
          <% @star_courses.each do |course| %>
            <div class="course">
              <%= render "courses/course", :course => course %>
            </div>
          <% end %>
        </div>
        <%= link_to "查看所有课程", course_index_path(:sort => "star"), class: "all-courses-btn button" %>
      <% else %>
        <p>
        No Courses found
        </p>
      <% end %>
    </div>
    <div id="sorted-by-time" style="display: none;">
      <% if !@recent_courses.empty? %>
        <div class="courses clearfix">
          <% @recent_courses.each do |course| %>
            <div class="course">
              <%= render "courses/course", :course => course %>
            </div>
          <% end %>
        </div>
        <%= link_to "查看所有课程", course_index_path(:sort => "time"), class: "all-courses-btn button" %>
      <% else %>
        <p>
        No Courses found
        </p>
      <% end %>
    </div>
  </div>

</div>

<% content_for :template_js do %>
  <script>
    var menuItems = $(".sort-label li");

    menuItems.on("click", function(event) {

      menuItems.removeClass("active");
      $(this).addClass("active");

      var type = $(this).data("type");

      if (type == "star") {
        $("#sorted-by-time").css("display", "none");
        $("#sorted-by-star").css("display", "block");
      }else {
        $("#sorted-by-star").css("display", "none");
        $("#sorted-by-time").css("display", "block");
      }

      event.preventDefault();
    });
  </script>
<% end %>

app/views/shared/_member_list.html.erb
<ol class="member-list clearfix">
  <% members.each do |member| %>
    <li class="member-list-item">
      <%= link_to member_path(member.name) do %>
        <%= image_tag member.final_avatar_url, alt: "uprofile", :class => "gavatar" %>
      <% end %>
      <div class="member-list-container">
        <h3 class="member-name">
          <%= link_to member_path(member.name) do %>
            <%= member.name.truncate(16) %>
          <% end %>
        </h3>
        <p class="courses">courses: <%= member.courses.count %></p>
        <p class="comments">comments: <%= member.comments.count %></p>
        <p class="join-date">joined: <%= member.created_at.strftime("%Y-%m-%d") %></p>
      </div>
    </li>
  <% end %>
</ol>

app/views/shared/_tagline.html.erb
<div class="tagline">
  <h1 class="heading">让视频课程发布更简单</h1>
  <div class="subheading">
    <p>
    尽早发布课程，获得用户反馈，然后逐步完善，最后完成满足用户需求的课程
    </p>
    <p>
    <a href="/about/faq#why-publish-uncompleted">为什么发布未完成的课程？</a>
    </p>
  </div>
</div>