config/routes.rb
Onestep::Application.routes.draw do

  root :to => 'info#marketing'
  get '/api/money'  => 'api#money'

  get 'timeline' => "activities#timeline", as: "timeline"

  post '/checkout' => "orders#checkout"
  get '/orders/done' => "orders#done"
  post '/orders/notify' => "orders#notify"
  get "/orders/new" => "orders#new",  :as => "new_order"
  get "/download" => "videos#download", :as => "download_video"

  get "about" => "about#main", :as => "about"
  get "about/team" => "about#team"
  get "about/jobs" => "about#jobs"
  get "about/faq" => "about#faq"
  get "/set_locale" => "info#set_locale"
  get "/styleguide/css(/:ref)" => "info#styleguide"

  get "/blog" => "posts#index", :as => "blogs"
  get "/blog/:id" => "posts#show", :as => "blog"
  get "/blog/:id/edit" => "posts#edit", :as => "edit_blog"
  get "/write_blog" => "posts#new"

  # Use patch verb for editing posts, use put verb for creating a new post
  match 'blog_images', to: 'blog_images#create', via: [:put, :patch]

  resources :posts
  resources :blog_images
  resources :videos
  resources :password_resets

  get "notifications" => "notifications#index", :as => "notifications"
  delete "notifications/:id" => "notifications#destroy", :as => "notification"
  delete "notifications" => "notifications#clear", :as => "clear_notifications"

  patch '/restore_gravatar' => "users#restore_gravatar"
  patch 'edit-avatar' => 'users#update_avatar', :as => :update_avatar
  get "edit-avatar" => "users#edit_avatar", :as => "edit_avatar"
  patch 'update_poster' => 'courses#update_poster', :as => :update_poster

  resources :comments
  post "/comment_preview" => "comments#preview", :as => "comment_preview"

  get "login" => "users#login", :as => "login"
  get "signup" => "users#signup", :as => "signup"
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"

  patch "/course" => "courses#update"
  get "/course" => "courses#index", :as => "course_index"
  post "/course" => "courses#create"
  get "/create_course" => "courses#new", :as => :create_course

  get "/members" => "users#index", :as => "user_index"
  post "/members" => "users#create"
  put "/crop" => "users#crop", :as => "crop"
  put "/crop_poster" => "courses#crop_poster", :as => "crop_poster"

  get "/:member_name/:course_name/timeline" => "activities#index" , :as => "timeline_course"

  post "/:member_name/:course_name/watch" => "courses#watch"
  post "/:member_name/:course_name/unwatch" => "courses#unwatch"
  get "/:member_name/:course_name/watchers" => "courses#watchers", :as => "course_watchers"

  get "/:member_name/:course_name/collaboration" => "courses#collaboration", :as => "course_collab"

  post "/:member_name/:course_name/add_member" => "courses#add_member", :as => "course_add_member"
  post "/:member_name/:course_name/delete_member" => "courses#delete_member", :as => "course_delete_member"

  resources :courses, :except => :edit do
    get :autocomplete_user_name, :on => :collection
  end

  post "/:member_name/follow" => "users#follow"
  post "/:member_name/unfollow" => "users#unfollow"

  get "/account" => "users#edit", :as => "account"
  patch "/account" => "users#update"
  get "/:member_name" => "users#show", :as => "member"
  delete "/:member_name/:course_name" => "courses#destroy"
  get "/:member_name/:course_name(/:position)" => "courses#show", :constraints => {:position => /\d+/} # "/:xxx/:xxx" will conflict with many things, so have to put bottom
  patch "/update_video/:id" => "videos#update"
  post "/sort_videos" => "videos#sort"

end

app/controllers/courses_controller.rb
# encoding: utf-8
class CoursesController < ApplicationController
  before_filter :check_owner, :only => [:edit, :update, :destory, :collaboration, :add_member, :delete_member]
  before_filter :find_course, :except => [:new, :index, :create, :update, :update_poster, :autocomplete_user_name]

  autocomplete :user, :name

  def index
    if params[:sort] == "time"
      @courses = Course.where(public: true).reverse
      @course_groups = []
      @courses.in_groups_of(3, false) { |group| @course_groups << group }
    elsif params[:sort] == "star"
      c_sorted = courses_sorted_by_star
      @course_groups = []
      c_sorted.in_groups_of(3, false) { |group| @course_groups << group }
    end
  end

  def show
    if @course.nil?
      redirect_to(:root, :notice => '抱歉，您访问的课程不存在')
    else
      if params[:position].present?
        @video = Video.where(:course_id => @course.id,:position => params[:position].to_i).first
      elsif @course.videos.empty?
        @video = nil
      else
        @video = Video.where(:course_id => @course.id,:position => 1).first
      end
      @video_link = Settings.video.store + @course.user.name + "/" + @course.name + "/" +  @video.position.to_s + ".mp4"
      session[:return_to] = request.url
    end
  end

  def watch
    @course.add_watcher(current_user)
    Notification.notify @course.user, @course, current_user, "watch"
    render :text => "1"
  end

  def unwatch
    @course.delete_watcher(current_user)
    render :text => "1"
  end

  def watchers
    @watchers = @course.watchers
  end

  def collaboration
    @collaborators = @course.collaborators
  end

  def add_member
    @member = User.find_by_name(params[:collab])
    if @course.user.id == @member.id
      @author_flag = true
      return
    end
    if @course.collaborators.include?(@member)
      @collab_flag = true
      return
    end
    @course.collaborators << @member
    respond_to do |format|
      format.js
    end
  end

  def delete_member
    @member = User.find_by_name(params[:collab])
    @course.collaborators.delete(@member)
    respond_to do |format|
      format.js
    end
  end

  private

  def find_course
    @user = User.find_by_name(params[:member_name])
    @course = Course.where(:user_id => @user.id, :name => params[:course_name]).first
  end

  def check_owner
    if current_user.nil?
      redirect_to :root, :notice => t('login_first_plz')
      return
    end
    if params[:course_name]
      user = User.find_by_name(params[:member_name])
      course = Course.where(:user_id => user.id, :name => params[:course_name]).first
    else
      # for update; find the proper course object when course title is blank
      course = Course.find(params[:course][:id])
    end
    if not (( current_user.admin? ) || (course.user == current_user))
      redirect_to :root, :notice => "抱歉，只有课程所有者或管理员才有此权限"
      return
    end
  end
end

app/helpers/courses_helper.rb
# encoding: utf-8
module CoursesHelper
  def course_watch_tag(course)
    return "" if course.blank?
    return "" if owner?(course)
    class_name = "watch"
    text = t('watch_course')
    if current_user.blank?
      title = "您必须登录后才能关注课程"
      return link_to text, login_url, :class => "minibutton with-count", :title => title, :rel => "twipsy"
    end
    if course.watchers.include?(current_user)
      class_name = "watched"
      text = t('unwatch_course')
    end
    link_to text, "#", :onclick => "return Courses.watch(this);",
            :class => "minibutton with-count",
            'data-user' => course.user.name,
            'data-course' => course.name,
            'data-watched' => (class_name == "watched")
  end
end

app/views/courses/_all_added_videos.html.erb
<div class="playlist-container">
  <ul id="play-list" class="playlist" data-update-url="/sort_videos">
    <% course.videos.each do |video| %>
      <%= content_tag_for :li, video do %>
        <a class="video" href="<%= course_path(video.course) + '/' + video.position.to_s + '/edit.js' %>" data-remote='true'>
          <span class="video-info edit-video-info">
            <%= video.title %>
            <%= "(免费)" if video.free? && paid_course?(course) %>
          </span>
        </a>
        <a href="<%= course_path(video.course) + '/' + video.position.to_s + '/edit.js' %>"
          data-remote='true'>
          <div class="pencil-icon">
             <i class="fa fa-pencil"></i>
          </div>
        </a>
      <% end %>
    <% end %>
    <li class="add-video-btn">
      <%= link_to course_path(course) + '/add_video.js', class: "video active", remote: true do %>
        <div class="video-icon">
          <i class="fa fa-plus fa-lg"></i>
        </div>
        <span class="video-info"> 添加新视频</span>
      <% end %>
    </li>
  </ul>
</div>

<%= content_for :template_js do %>
  <script>
    $("ul.playlist > li").hover(
      function() {
        var text = "<div class='list-icon'><i class='fa fa-th-list'></i></div>";
        var a = $(this).hasClass('video');
        if(a == true) {
          $(this).prepend(text);
        }
      },
      function() {
        $("div.list-icon").remove();
      }
    );

    $(function() {
      $('#play-list').sortable({
        axis: 'y',
        cancel: 'a',
        update: function() {
          $.post($(this).data('update-url'), $(this).sortable('serialize'));
          location.reload();// to update all the position value
        }
      });
    });
  </script>
<% end %>

app/views/courses/_collaborator.html.erb
<li class="uid_<%= user.id %>">
  <%= link_to member_path(user.name)  do %>
    <%= image_tag user.final_avatar_url, :class => "collab-avatar" %>
    <span><%= user.name %></span>
    <%= link_to course_delete_member_path(:collab => user.name), :method => :post,
      :remote => true, :class => "delete-collab-button" do %>
      <i class="fa fa-times-circle-o"></i>
    <% end %>
  <% end %>
</li>

app/views/courses/_course.html.erb
<%= link_to course_path(course), class: "course-thumb-container clearfix" do %>
  <div class="course-thumb center-course-thumb light-shadow">
    <div class="course-main">
      <%= image_tag course.poster_url %>
      <div class="course-title">
        <%= course.title %>
        <% if !course.public %>
          <div class="course-private-label"><i class="fa fa-lock fa-2x"></i></div>
        <% end %>
      </div>
      <div class="course-desc">
        <%= course.description %>
      </div>
      <div class="course-author">
        <%= image_tag course.user.final_avatar_url, class: "course-thumb-avatar" %>
        <%= course.user.name %>
      </div>
    </div>
  </div>
<% end %>

app/views/courses/_course_list.html.erb
<div class="course-list clearfix">
  <div class="user-course-header">
    <i class="fa fa-clock-o"></i>
    <span class="date"><%= course.created_at.strftime("%B %d, %Y") %></span>
    <span class="watcher">/ 关注人数 <%= course.watchers.count %></span>
  </div>
  <%= link_to course_path(course) do %>
    <%= image_tag course.poster_url %>
  <% end %>
  <div class="meta">
    <div>
      <span class="title"><%= link_to course.title, course_path(course) %></span>
      <% if !course.public %>
        <span class="lock"><i class="fa fa-lock fa-lg"></i></span>
      <% end %>
    </div>
    <div class="desc">
      <%= course.description %>
    </div>
    <div class="details">
      <i class="fa fa-video-camera"></i><span class="tip">视频: <%= course.videos.count %></span>
    </div>
    <div class="details">
      <i class="fa fa-money"></i><span class="tip">价格: <%= course.price.present? ? course.price : 0 %> 元</span>
    </div>
    <div class="details">
      <i class="fa fa-user"></i><span class="tip">作者: <%= link_to course.user.name, member_path(course.user.name) %></span>
    </div>
  </div>
  <%= link_to "查看课程", course_path(course), :class => "course-button" %>
</div>

app/views/courses/_form.html.erb
<% content_for :template_js do %>
  <script>
    $('#course_desc').NobleCount('#desc_count',{
      on_negative: 'go_red',
      on_positive: 'go_green',
      max_chars: 33});
  </script>
<% end %>
<%= form_for(@course, :url => "/course") do |f| %>
  <%= f.hidden_field :user_id %>
  <%= flash[:notice] %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <dl class="form">
    <dt> <%= f.label t('course_title') %> </dt>
    <dd> <%= f.text_field :title %> </dd>
  </dl>
  <div>
    <%= f.submit "创建课程", :class => "minibutton primary" %>
  </div>
<% end %>

app/views/courses/_play_list.html.erb
<div class="playlist-container">
  <ul class="playlist">
    <% course.videos.each do |v| %>
      <li>
      <a class="video <%= "active" if v.position == current_video.position %>" href="<%= course_path(v.course) + "/" + v.position.to_s %>">
        <div class="video-icon">
          <i class="fa fa-video-camera fa-lg"></i>
        </div>
        <span class="video-info">
          <%= v.title %>
          <%= "(免费)" if v.free? && paid_course?(course) %>
        </span>
      </a>
      </li>
    <% end %>
  </ul>
</div>

app/views/courses/_video_info.html.erb
<div id="video-info" class="tutorial-description">
  <h3><%= video.title %></h3>
  <p>
    <%= auto_link video.desc %>
  </p>
</div>

app/views/courses/_video_player.html.erb
<video id="html5-player" class="video-js vjs-default-skin" controls preload="auto"
  width="840" height="<%= (840 / video.ratio).to_i %>" data-setup="{}">
  <source src="<%= video_link %>" type='video/mp4'>
</video>
<div class="download-btn">
  <a class="minibutton primary" href="<%= video_link %>">Download</a>
</div>

app/views/courses/add_member.js.erb
<% if @author_flag %>
  $('.collab-error').html("<%= t('course_author_cannot_be_a_collaborator') %>!")
  $('.collab-error').css("display", "block");
<% elsif @collab_flag %>
  $('.collab-error').html("<%= t('you_have_added') %> <%= @member.name %> !")
  $('.collab-error').css("display", "block");
<% else %>
  $('.collabs').append("<%= j render 'collaborator', :user => @member %>")
<% end %>

app/views/courses/collaboration.html.erb
<div class="container">
  <div class="collab-wrapper">
    <div class="caption">
      <%= t('collaborator') %><small class="free"><%= t('watch_course_no_fee') %></small>
      <span><%= link_to t('go_back'), @course, :class => "minibutton" %></span>
    </div>
    <ul class="collabs">
      <% if @collaborators.present? %>
        <% @collaborators.each do |user| %>
          <li class="uid_<%= user.id %>">
            <%= link_to member_path(user.name) do %>
              <%= image_tag user.final_avatar_url, :class => "collab-avatar" %>
              <span><%= user.name %></span>
            <% end %>
            <%= link_to course_delete_member_path(:collab => user.name), :method => :post,
              :remote => true, :class => "delete-collab-button" do %>
              <i class="fa fa-times-circle-o"></i>
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>

    <%= form_tag course_add_member_path, :class => "add-new-collab", :method => :post, :remote => true do %>
      <div class="form-wrapper">
        <%= autocomplete_field_tag :collab, params[:collab], autocomplete_user_name_courses_path, :size => 25, :placeholder => t('type_a_user_name') %>
        <%= button_tag :type => "submit", :class => "collab-button", :disabled => true do %>
          <%= t('add_collaborator') %>
        <% end %>
      </div>
    <% end %>

    <div class="collab-error"></div>
  </div>
</div>
<% content_for :template_js do %>
  <script>
    $('#collab').focus(function() {
      $('.ui-helper-hidden-accessible').css("display", "none");
    });
    $('#collab').bind('input', function() {
      $('.collab-button').attr("disabled", true);
    });
    $('#collab').bind('railsAutocomplete.select', function(){
      $('.collab-button').attr("disabled", false);
    });
  </script>
<% end %>

app/views/courses/delete_member.js.erb
$("li.uid_<%= @member.id %>").remove();

app/views/courses/index.html.erb
<div class="container marketing">

  <% if !@course_groups.empty? %>
    <% @course_groups.each do |row| %>
      <div class="courses">
        <% row.each do |course| %>
          <div class="course">
            <%= render course %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <p>
    No Courses found
    </p>
  <% end %>
</div>

app/views/courses/show.html.erb
<div class="pagehead clearfix">
  <div class="container">
    <ul class="pagehead-actions">
      <% if owner?(@course) %>
        <% if paid_course?(@course) %>
          <li><%= link_to t('add_collaborator'), course_collab_path, :class => "minibutton" %></li>
        <% end %>
      <% end %>
      <% if not @course.open_to_user?(current_user) %>
        <li>
          <%= link_to t('buy_this_course') + "（￥" + @course.price.to_s + "）", new_order_path + "?course_id=#{@course.id}", :class => "minibutton primary" %>
        </li>
      <% end %>
      <li>
      <%= course_watch_tag(@course) %>
      <% if owner?(@course) %>
        <%= link_to "关注人数", course_watchers_path, :class => "social-count-title" %>
      <% end %>
      <%= link_to @course.watchers.count, course_watchers_path, :class => "social-count" %>
      </li>
    </ul>
    <h1 class="pagehead-heading">
      <div class="course-image" style="background-image: url(<%= @course.poster_url %>);"></div>
      <span class="author">
        <%= link_to @course.user.name, member_path(@course.user.name), :class => "author" %>
      </span>
      <span class="pagehead-name-divider">/</span>
      <strong><%= link_to @course.title, course_path(@course) %></strong>
      <% if !paid_course?(@course) %>
        <span class="ui teal label">免费</span>
      <% end %>
    </h1>
    <br>
    <p class="course-desc"><%= auto_link @course.description %></p>
  </div>
</div>
<div class='container'>
  <% if not @video %>
    <h1><%= @course.title %></h1>
    <div class="alert">
      <%= t('no_classes') %>
      <% if owner?(@course) %>
        <%= link_to t('edit_course'), edit_course_path(@course), :class => "minibutton" %>
        <%= link_to t('delete_this_course'), @course, :confirm => t('confirm_delete'),
          :method => :delete, :class => "minibutton" %>
      <% end %>
    </div>
  <% else %>

    <div class="tutorial-page">
      <div class="tutorial-nav">
        <%= render "play_list", :course => @course, :current_video => @video %>
        <div class="course-update-time">
          <i class="fa fa-clock-o"></i>
          <span><%= t('update_time') %></span>
          <span><%= link_to @course.updated_at.strftime(t('date.formats.default')), timeline_course_path %></span>
        </div>

      </div>
      <div class="tutorial-content">
        <%= render "video_info", :video => @video %>
        <% if @course.open_to_user?(current_user) || @video.open_to_user?(current_user) %>
          <%= render :partial => "video_player", :locals => {:video => @video, :video_link => @video_link } %>
        <% else %>
          <%= link_to t('pay_for_course_please'), new_order_path + "?course_id=#{@course.id}",
            :class => "button primary" %>
        <% end %>
        <div id="comments">
          <h3><%= t("comment") %></h3>
          <%= render @video.comments %>
        </div>
        <% if current_user %>
          <%= render "comments/new_comment_form", :commentable => @video %>
        <% else %>
          <div id="login_buttons">
            <%= link_to t("login_and_comment"), login_path(:return_to => request.url),
              :class => "minibutton primary" %>
          </div>
          <br>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<% content_for :template_js do %>
  <script>
    $("textarea#comment_content").keydown(function(e) {
      if ((e.ctrlKey||e.metaKey) && e.keyCode == 13) {
        $("input[type=submit]").click();
      }
    });
  </script>
<% end %>

app/views/courses/watchers.html.erb
<div class="container">
  <div id="watcher-page">
    <div class="title">
      <%= t 'watchers' %> <%= @watchers.count %>
    </div>
    <% if @watchers.blank? %>
      <%= t 'no_watcher_found' %>
    <% else %>
      <%= render :partial => "shared/member_list", :locals => {:members => @watchers} %>
    <% end %>
  </div>
</div>