config/routes.rb
Onestep::Application.routes.draw do

  root :to => 'info#marketing'
  get '/api/money'  => 'api#money'

  get 'timeline' => "activities#timeline", as: "timeline"

  post '/checkout' => "orders#checkout"
  get '/orders/done' => "orders#done"
  post '/orders/notify' => "orders#notify"
  get "/orders/new" => "orders#new",  :as => "new_order"
  get "/download" => "videos#download", :as => "download_video"

  get "about" => "about#main", :as => "about"
  get "about/team" => "about#team"
  get "about/jobs" => "about#jobs"
  get "about/faq" => "about#faq"
  get "/set_locale" => "info#set_locale"
  get "/styleguide/css(/:ref)" => "info#styleguide"

  get "/blog" => "posts#index", :as => "blogs"
  get "/blog/:id" => "posts#show", :as => "blog"
  get "/blog/:id/edit" => "posts#edit", :as => "edit_blog"
  get "/write_blog" => "posts#new"

  # Use patch verb for editing posts, use put verb for creating a new post
  match 'blog_images', to: 'blog_images#create', via: [:put, :patch]

  resources :posts
  resources :blog_images
  resources :videos
  resources :password_resets

  get "notifications" => "notifications#index", :as => "notifications"
  delete "notifications/:id" => "notifications#destroy", :as => "notification"
  delete "notifications" => "notifications#clear", :as => "clear_notifications"

  patch '/restore_gravatar' => "users#restore_gravatar"
  patch 'edit-avatar' => 'users#update_avatar', :as => :update_avatar
  get "edit-avatar" => "users#edit_avatar", :as => "edit_avatar"
  patch 'update_poster' => 'courses#update_poster', :as => :update_poster

  resources :comments
  post "/comment_preview" => "comments#preview", :as => "comment_preview"

  get "login" => "users#login", :as => "login"
  get "signup" => "users#signup", :as => "signup"
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"

  patch "/course" => "courses#update"
  get "/course" => "courses#index", :as => "course_index"
  post "/course" => "courses#create"
  get "/create_course" => "courses#new", :as => :create_course

  get "/members" => "users#index", :as => "user_index"
  post "/members" => "users#create"
  put "/crop" => "users#crop", :as => "crop"
  put "/crop_poster" => "courses#crop_poster", :as => "crop_poster"

  get "/:member_name/:course_name/timeline" => "activities#index" , :as => "timeline_course"

  post "/:member_name/:course_name/watch" => "courses#watch"
  post "/:member_name/:course_name/unwatch" => "courses#unwatch"
  get "/:member_name/:course_name/watchers" => "courses#watchers", :as => "course_watchers"

  get "/:member_name/:course_name/collaboration" => "courses#collaboration", :as => "course_collab"

  post "/:member_name/:course_name/add_member" => "courses#add_member", :as => "course_add_member"
  post "/:member_name/:course_name/delete_member" => "courses#delete_member", :as => "course_delete_member"

  resources :courses, :except => :edit do
    get :autocomplete_user_name, :on => :collection
  end

  post "/:member_name/follow" => "users#follow"
  post "/:member_name/unfollow" => "users#unfollow"

  get "/account" => "users#edit", :as => "account"
  patch "/account" => "users#update"
  get "/:member_name" => "users#show", :as => "member"
  delete "/:member_name/:course_name" => "courses#destroy"
  get "/:member_name/:course_name(/:position)" => "courses#show", :constraints => {:position => /\d+/} # "/:xxx/:xxx" will conflict with many things, so have to put bottom
  patch "/update_video/:id" => "videos#update"
  post "/sort_videos" => "videos#sort"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :name

  belongs_to :user

  has_many :comments, :as => :commentable, :dependent => :destroy

  scope :recent, -> { order('id DESC') }

  def to_param
  # post_path(@post), will become blog/0112-good-news
    "#{id} #{name}".parameterize
  end
end

app/controllers/posts_controller.rb
# encoding: utf-8
class PostsController < ApplicationController
  before_filter :check_admin, :except => [:index, :show]

  def index
    @posts = Post.recent
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(params[:post])
    title = params[:post][:title]
    name = PinYin.of_string(title).join('-').downcase
    post.user_id = current_user.id
    post.name = name
    if post.save
      redirect_to blog_path(post), :notice => "博客创建成功"
    else
      render "new"
    end
  end

  def update
    @post = Post.find(params[:id])
    title = params[:post][:title]
    name = PinYin.of_string(title).join('-').downcase
    @post.name = name
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to blog_path(@post), :success => '博客更新成功' }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def show
    @post = Post.find(params[:id])
    session[:return_to] = request.url
  end

  def edit
    @post = Post.find(params[:id])
  end
end

app/views/posts/_blog_form.html.erb
<div class="container">
  <div class="box">
    <div class="box-header"> </div>
    <div class="inner">
      <%= form_for @post do |f| %>
        <%= f.text_field :title %>
        文章标题
        <br> <br>
        <%= render 'shared/fileupload_widget', :textarea_selector => "textarea#post_content" %>
        <%= f.text_area :content , :id => "post_content", :row => 5, :style => "width: 100%" %>
        <br>
        <%= f.submit :class=>"minibutton" %>
      <% end %>
    </div>
  </div>

app/views/posts/_post.html.erb
<div class="blog-post">
  <h2 class="blog-post-title">
    <%= link_to post.title, blog_path(post) %>
  </h2>
  <ul class="blog-post-meta">
    <li>
      <i class="fa fa-calendar"></i>
      <%= post.created_at.strftime('%Y-%m-%d') %>
    </li>
    <li>
      <%= image_tag post.user.final_avatar_url, :alt => "头像", :class => "author-avatar" %>
      <% if post.user %>
        <%= link_to post.user.name, member_path(post.user.name) %>
      <% end %>
    </li>
  </ul>
  <div class="blog-markdown-body markdown-format">
    <%= markdown post.content %>
    <% if current_user && current_user.admin? %>
      <%= link_to t("edit_blog"), edit_blog_path(post), :class => "minibutton" %>
    <% end %>
  </div>
  <div class="blog-comments">
    <%= link_to "#{blog_path(post)}#comments" do %>
      <%= post.comments.count %> 评论
     <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render "blog_form" %>

app/views/posts/index.html.erb
<div class="container">
  <div class="blog">
    <% if current_user && current_user.admin? %>
      <div class="minibutton">
        <%= link_to "写文章", "/write_blog" %>
      </div>
    <% end %>
    <div class="post-listing">
      <% if @posts.empty? %>
        <p>
          目前还没有任何文章
        </p>
      <% else %>
        <%= render @posts %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render "blog_form" %>

app/views/posts/show.html.erb
<div class="container">
  <div class="blog">
      <div class="post-listing">
        <%= render @post %>
      <div id="comments">
        <h3><%= t("comment") %></h3>
        <%= render @post.comments %>
      </div>
      <% if current_user %>
        <%= render "comments/new_comment_form", :commentable => @post %>
      <% else %>
        <div id="login_buttons">
          <%= link_to t("login_and_comment"), login_path(:return_to => request.url),
            :class => "minibutton primary" %>
        </div>
        <br>
      <% end %>
    </div>
  </div>
</div>